server:
    port: 8000
mysql:
    user: root
    pass: ecommerce@123
    host: localhost
    port: 33306
    db_name: ecommerce
    max_idle_conn: 10
    max_open_conn: 100
    conn_max_life_time: 3600