server:
    port: 8000
mysql:
    user: root
    pass: ecommerce@123
    host: localhost
    port: 33306
    db_name: ecommerce
    max_idle_conn: 10
    max_open_conn: 100
    conn_max_life_time: 3600
log:
    log_level: debug
    file_name: "./logs/dev.001.log"
    max_size: 500
    max_backups: 3
    max_age: 28
    compress: true
redis:
    host: localhost
    port: 6380
    password: 123456
    db: 0
    pool_size: 100
