server:
    port: 8000
databases:
    - user: admin
      pass: admin
      host: localhost
      db_name: auth
    - user: ecommerce
      pass: ecommerce
      host: localhost
      db_name: ecommerce